// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUp8f5PCqhhJ9FMhygPBh272JqCV_ODyg',
    appId: '1:650838540527:web:fce6b30bd668085f235b1a',
    messagingSenderId: '650838540527',
    projectId: 'flutterchatapp-8e23a',
    authDomain: 'flutterchatapp-8e23a.firebaseapp.com',
    storageBucket: 'flutterchatapp-8e23a.firebasestorage.app',
    measurementId: 'G-MHWP3J6NVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKLQn3nPqspnKYd5ILTqQ3jJN3VOsViEc',
    appId: '1:650838540527:android:d180f92058f778a9235b1a',
    messagingSenderId: '650838540527',
    projectId: 'flutterchatapp-8e23a',
    storageBucket: 'flutterchatapp-8e23a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk6o0W9EsmSPHmYAgqj-UWFyDxPW-O09o',
    appId: '1:650838540527:ios:fcecea8cb5fc53dd235b1a',
    messagingSenderId: '650838540527',
    projectId: 'flutterchatapp-8e23a',
    storageBucket: 'flutterchatapp-8e23a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUp8f5PCqhhJ9FMhygPBh272JqCV_ODyg',
    appId: '1:650838540527:web:49d430ae82b53df1235b1a',
    messagingSenderId: '650838540527',
    projectId: 'flutterchatapp-8e23a',
    authDomain: 'flutterchatapp-8e23a.firebaseapp.com',
    storageBucket: 'flutterchatapp-8e23a.firebasestorage.app',
    measurementId: 'G-8MZ34T2X03',
  );
}
