// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYF-ItRyOhAsOqTNwhTcy6imy71d9zMuM',
    appId: '1:1023709643929:web:a1218343cc577787902408',
    messagingSenderId: '1023709643929',
    projectId: 'chatapp-a671e',
    authDomain: 'chatapp-a671e.firebaseapp.com',
    storageBucket: 'chatapp-a671e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgmsNPwzTprhBxFjMSIZF9AiPqVLx1BdU',
    appId: '1:1023709643929:android:6eaf2c5ec9406163902408',
    messagingSenderId: '1023709643929',
    projectId: 'chatapp-a671e',
    storageBucket: 'chatapp-a671e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnflw4oOrODTFFp9bmgzlKLYOVHO9IPPs',
    appId: '1:1023709643929:ios:bfa827741f538346902408',
    messagingSenderId: '1023709643929',
    projectId: 'chatapp-a671e',
    storageBucket: 'chatapp-a671e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnflw4oOrODTFFp9bmgzlKLYOVHO9IPPs',
    appId: '1:1023709643929:ios:bfa827741f538346902408',
    messagingSenderId: '1023709643929',
    projectId: 'chatapp-a671e',
    storageBucket: 'chatapp-a671e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYF-ItRyOhAsOqTNwhTcy6imy71d9zMuM',
    appId: '1:1023709643929:web:72cf8b81203868bb902408',
    messagingSenderId: '1023709643929',
    projectId: 'chatapp-a671e',
    authDomain: 'chatapp-a671e.firebaseapp.com',
    storageBucket: 'chatapp-a671e.firebasestorage.app',
  );

}